couchdb :
  server    : http://0.0.0.0:5984/
  database  : albums

general:
  hostname  : 'ec2-35-158-214-100.eu-central-1.compute.amazonaws.com'
  host      : 0.0.0.0
  port      : 8080
  debug     : True

palettes:
  plain_black :
    name : 'Plain Black'
    img : 'plain_black.png'
    colors :
      - [0, 0, 0]

  thought_provoking :
    name : 'Thought Provoking'
    img : 'thought_provoking.png'
    colors :
      - [236,208,120]
      - [217,91,67]
      - [192,41,66]
      - [84,36,55]
      - [83,119,122]
      
  cheer_up :
    name : 'Cheer Up'
    img : 'cheer_up.png'
    colors :
      - [85,98,112]
      - [78,205,196]
      - [199,244,100]
      - [255,107,107]
      - [196,77,88]